### ISSUE TITLE
Appsettings json configuration mismatch

### ISSUE THREAD

**Issue by FrankDupree** [dotnet-architecture/eShopOnContainers#1014]
I tried running the WebMVC project and got this error:
```
Program terminated unexpectedly (WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
```
Code where error is thrown in Startup.cs
https://github.com/dotnetarchitecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs#L144
```
public static IServiceCollection AddHealthChecks(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddHealthChecks()
                .AddCheck("self", () => HealthCheckResult.Healthy())
                .AddUrlGroup(new Uri(configuration["PurchaseUrlHC"]), name: "purchaseapigw-check", tags: new string[] { "purchaseapigw" })
                .AddUrlGroup(new Uri(configuration["MarketingUrlHC"]), name: "marketingapigw-check", tags: new string[] { "marketingapigw" })
                .AddUrlGroup(new Uri(configuration["IdentityUrlHC"]), name: "identityapi-check", tags: new string[] { "identityapi" });                
            
            return services;
        }
```

Appsettings.json file:
https://github.com/dotnetarchitecture/eShopOnContainers/blob/dev/src/Web/WebMVC/appsettings.json
```
{
  "CatalogUrl": "http://localhost:5101",
  "OrderingUrl": "http://localhost:5102",
  "BasketUrl": "http://localhost:5103",
  "MarketingUrl": "http://localhost:5110",
  "IdentityUrl": "http://localhost:5105",
  "CallBackUrl": "http://localhost:5100/",
  "LocationsUrl": "http://localhost:5109/",
    ....
}
```

Notice there is no entry for "**IdentityUrlHC**".  instead we have "**IdentityUrl**"

**Comment by mvelosop** [comment]
Hi @FrankDupree,

I guess you're trying to run the app from VS instead that from the container, right?

If that's the case, then the proper solution would be to add the `*HC` configuration parameters to `appsettings.json`.

This is so, because when running from the container those config params are taken from here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/73d0c3f659b3cecf9ada2fdd7c09db679e40d1e6/docker-compose.override.yml#L394-L396

Referencing the internal (Docker network) "machine" names, overriding whatever you have in `appsettings.json`.

But when running from VS you have to reference `localhost`, so `appsettings.json` must include those very same params but with **localhost** values.

Would you like to fix that in a PR? 

Cheers 😊

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.

**Comment by sheng-jie** [comment]
@mvelosop Hi, mvelosop. I got this error when I tried to deploy the 3.0 release to AKS.  Other services is ok, only WebMvc cannot start. 
![](https://user-images.githubusercontent.com/12607748/71640372-9ba8d780-2cc3-11ea-97f9-f873d73749ef.png)

```
kubectl logs eshop-webmvc-764b6749bb-td9sh
[10:18:14 INF] Configuring web host (eShopOnContainers.WebMVC)...
[10:18:15 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in /src/src/Web/WebMVC/Startup.cs:line 140
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in /src/src/Web/WebMVC/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in /src/src/Web/WebMVC/Program.cs:line 24
```
I checked the deployment of eshop-webmvc and configmap of  cfg-eshop-webmvc and all looks good.
I tried to edit deployment of eshop-webmvc and set env `IdentityUrlHC` to http://identity-api/hc directly and redeploy it but still cannot work. 
```
        - name: IdentityUrlHC
          value: http://identity-api/hc
```
I am not family with k8s, so I don't have any idea on that. Can you help? Thanks.

**Comment by SVronskiy** [comment]
Same error here in k8s on-premises, webmvc. Who khows how to fix it?
```
[10:51:32 INF] Configuring web host (eShopOnContainers.WebMVC)...
[10:51:32 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in /src/src/Web/WebMVC/Startup.cs:line 140
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in /src/src/Web/WebMVC/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in /src/src/Web/WebMVC/Program.cs:line 24
```

**Comment by jarz** [comment]
I have a hunch: the images being pulled from DockerHub aren't up to date with the code.

I saw this a few weeks ago when playing around. I had to jump back to code from early 2019 to see a few additional settings that don't currently exist in the repo.
