### ISSUE TITLE
Help with - The physical path is '/app/configuration/configuration.json'.

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1067]
Staff all good>
I understand that the "/ app" is the mapping of the app in the container, but I'm a little lost with the problem with the file, could they help me?

ERROR:
The configuration file 'configuration/configuration.json' was not found and is not optional. The physical path is '/app/configuration/configuration.json'.

   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OcelotApiGw.Program.BuildWebHost(String[] args) in C:\Users\xxxx\Documents\GitHub\eShopOnContainers\src\ApiGateways\ApiGw-Base\Program.cs:line 41
 at OcelotApiGw.Program.Main(String[] args) in C:\Users\andrei\Documents\GitHub\eShopOnContainers\src\ApiGateways\ApiGw-Base\Program.cs:line 19

**Comment by mvelosop** [comment]
Hi @pabloandrei, 

Could you please elaborate on your context?

It looks like you were trying to run the OcelotApiGw from VS! is that so?

**Comment by pabloandrei** [comment]
Good afternoon.

Yes, I updated the project (I downloaded the latest version of the branch) and the problem stopped. I must have changed something erratically.
