### ISSUE TITLE
OException: IDX20804: Unable to retrieve document from: '[PII is hidden]'.

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1126]
Hello, the error occurred when try login in the solution.
Anybody see this error?
Sincerely,
Pablo

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by pabloandrei** [comment]
in addition ...
I added the code below in WebMVC- public void ConfigureServices(IServiceCollection services)
            IdentityModelEventSource.ShowPII = true; 

Without success, alias, return other error.


Im using last version of dev branch.

Sincerely,
Pablo

**Comment by mvelosop** [comment]
Hi @pabloandrei,

This seems to be a networking problem too.

What's your setup? corporate firewall or VPN?

Did you check the [Windows setup wiki page (networking section)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-local-networking) and the [Additional resources section in the same page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#additional-resources).

More specifically, the issue https://github.com/dotnet-architecture/eShopOnContainers/issues/295#issuecomment-327973650?

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by austinlounds** [comment]
@mvelosop I am having the same issue. I can run the containers and navigate to localhost:5100 but when i try to login I get the exception page attached.  I am on a work machine with a symantec endpoint protection running. I want to assume there is some conflict with the firewall rules I set up with the script and a setting within Symantec. 
Any feedback on solutions would be appreciated
![image](https://user-images.githubusercontent.com/16471611/84949713-a6152d00-b0bb-11ea-928b-525256cb942b.png)

**Comment by alecvolo** [comment]
For Windows, in the docker-compose.override.yml file try to change 
` IdentityUrl=http://10.0.75.1:5105 `
on
` IdentityUrl=http://docker.for.win.localhost:5105 `
