### ISSUE TITLE
Error: Value cannot be null for webmvc project 

### ISSUE THREAD

**Issue by siddheshGit** [dotnet-architecture/eShopOnContainers#1252]
Hello there

i am getting below error in webmvc pod, its resulting 'CrashLoopBackOff' status for this pod.

[16:58:46 INF] Configuring web host (eShopOnContainers.WebMVC)...
[16:58:48 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in C:\src\src\Web\WebMVC\Startup.cs:line 138
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in C:\src\src\Web\WebMVC\Startup.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in C:\src\src\Web\WebMVC\Program.cs:line 24

**Comment by sughosneo** [comment]
Hi @siddheshGit , thanks for the information. We have recently updated our local k8s and AKS related scripts. Could you please  take the latest from `dev` branch and see if it helps to resolve the issue ?

Here are the links for your reference - 

1) [Local K8s](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
2) [AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

**Comment by sughosneo** [comment]
Hi @siddheshGit , I am closing this issue as of now. But if you have any further questions, please feel free to reopen it. 

Thank you.
