### ISSUE TITLE
WebMVC pod failed to start when deployed to AKS

### ISSUE THREAD

**Issue by srinisachanta** [dotnet-architecture/eShopOnContainers#1305]
Hello
I followed instructions to setup in AKS  using official images.  I am seeing below errors in the pod logs. Any insights?

---------------
 kubectl logs eshop-webmvc-54746874cf-6k9mq

[19:35:22 INF] Configuring web host (eShopOnContainers.WebMVC)...
[19:35:23 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in /src/src/Web/WebMVC/Startup.cs:line 140
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in /src/src/Web/WebMVC/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in /src/src/Web/WebMVC/Program.cs:line 24

**Comment by mvelosop** [comment]
Hi @srinisachanta, thanks for the feedback.

I'll be reviewing all setup procedures shortly.

In the meantime try adding a line similar to:
https://github.com/dotnet-architecture/eShopOnContainers/blob/b1021c88d55d96c247eab75bde650ab4b194f706/deploy/k8s/helm/webmvc/templates/configmap.yaml#L20

but with the key: DPConnectionString, that is:

```yaml
DPConnectionString: {{ .Values.inf.redis.keystore.constr }} 
```

With the same indentation.

Hope this helps.

**Comment by srinisachanta** [comment]
Thanks for getting back @mvelosop. I updated the file but see the same error.

**Comment by rajarathinams** [comment]
Hi ,is the above issue resolved ? I am also facing the same issue.

Can you please update the status ?

**Comment by ahladh** [comment]
Hi @mvelosop,
I am also facing the same issue while deploying on local kubernetes.

Please, let me know anything else need to be updated.

**Comment by cchoygithub** [comment]
I'm having the same issue, with webmvc crashLoopbackoff to.

**Comment by chetanpjain** [comment]
Can someone suggest solution to this problem, I am also facing the same error on AKS cluster setup

**Comment by sughosneo** [comment]
Hi @srinisachanta , we have recently updated our scripts to support latest version of K8s in both local and aks related deployment.
Here is the [wiki reference](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)) for AKS related deployment. Could you please give it a try and see if that helps ?

Thanks.

**Comment by chetanpjain** [comment]
just tested the latest code, it is getting deployed successfully with helm3 on AKS cluster, will be trying to automate the deploy through azure devops on AKS cluster

**Comment by srinisachanta** [comment]
@sughosneo  awesome! will try this out over the weekend. Thanks so much.

**Comment by sughosneo** [comment]
Hi @chetanpjain , @srinisachanta -  considering updated deployment steps are working for you I am closing this issue as of now. If you face any challenges, please feel free to reopen it. 

Thank you.
