### ISSUE TITLE
MVC Webapp not displaying catalog images

### ISSUE THREAD

**Issue by rekhajay** [dotnet-architecture/eShopOnContainers#1359]
I cloned the dev branch, followed all the steps, and have the MVC Web App up and running. Everything is working, except I cannot see any of the catalog images.

Could not find file '/app/Pics/11.png'.
 
 Here is the output from the Logger:
 
 Download Raw JSON
ActionId
1d1417bc-5258-4ac6-bc6f-27745e5dad72
ActionName
Microsoft.eShopOnContainers.Services.Catalog.API.Controllers.PicController.GetImageAsync (Catalog.API)
ApplicationContext
Catalog.API
ConnectionId
0HM11R6N6TRQF
EventId
{Id: -2147024894}
ParentId
0000000000000000
RequestId
0HM11R6N6TRQF:0000000C
RequestPath
/catalog-api/api/v1/catalog/items/11/pic/
SourceContext
Catalog.API.Infrastructure.Filters.HttpGlobalExceptionFilter
SpanId
dde10f8f2a621549
TraceId
b89f3b95075e9d429dd841ad912ff31c
System.IO.FileNotFoundException: Could not find file '/app/Pics/11.png'.
File name: '/app/Pics/11.png'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.ReadAllBytes(String path)
   at Microsoft.eShopOnContainers.Services.Catalog.API.Controllers.PicController.GetImageAsync(Int32 catalogItemId) in C:\Users\rekha.jayaram\Source\Repos\eShopOnContainers\src\Services\Catalog\Catalog.API\Controllers\PicController.cs:line 49
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by rekhajay** [comment]
<img width="890" alt="eshopCapture" src="https://user-images.githubusercontent.com/48165295/86637991-5ffd0c00-bf8b-11ea-97b0-165e9233c6eb.PNG">

Please find attached image - showing issue.

**Comment by rekhajay** [comment]
figured out what the issue was - I did a compare of my local git repo to the dev branch and saw that for some reason the .png images in CatalogAPI folder were deleted. Not sure what caused this, but I just undid the action, restored the png's and now I can see the images

![image](https://user-images.githubusercontent.com/48165295/86640697-5f667480-bf8f-11ea-83f8-a4a7d9ccec68.png)
