### ISSUE TITLE
Error with MongoDB

### ISSUE THREAD

**Issue by dereklew** [dotnet-architecture/eShopOnContainers#1384]
I am running using the latest build, yet I am getting the following error, it seems not able to start MongoDB.

System.AggregateException: One or more errors occurred. (A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/nosqldata:27017" }", EndPoint: "Unspecified/nosqldata:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-08-01T15:27:12.0813400Z" }] }.)
 ---> System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/nosqldata:27017" }", EndPoint: "Unspecified/nosqldata:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-08-01T15:27:12.0813400Z" }] }.
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.Aggregate[TResult](PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.Linq.AggregateQueryableExecutionModel`1.Execute[TInput](IMongoCollection`1 collection, AggregateOptions options)
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.ExecuteModel(QueryableExecutionModel model)
   at MongoDB.Driver.Linq.MongoQueryableImpl`2.ToCursor(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.Any[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Microsoft.eShopOnContainers.Services.Locations.API.Infrastructure.LocationsContextSeed.SeedAsync(IApplicationBuilder applicationBuilder, ILoggerFactory loggerFactory) in /src/Services/Location/Locations.API/Infrastructure/LocationsContextSeed.cs:line 23
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.eShopOnContainers.Services.Locations.API.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory) in /src/Services/Location/Locations.API/Startup.cs:line 200
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Microsoft.eShopOnContainers.Services.Locations.API.Program.Main(String[] args) in /src/Services/Location/Locations.API/Program.cs:line 31

**Comment by dereklew** [comment]
I am getting this error as well.

Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade.

**Comment by sughosneo** [comment]
Hi @dereklew, when do you get to see this error message ? Could you please provide some more details ?

Thank you.

**Comment by dereklew** [comment]
The first exception came after dcoke-compose up,

**Comment by dereklew** [comment]
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
f0acf3b627c9        eshop/webmvc:linux-latest                     "dotnet WebMVC.dll"      2 hours ago         Up 4 minutes        0.0.0.0:5100->80/tcp                                                                         src_webmvc_1
e5aae5989532        eshop/ordering.signalrhub:linux-latest        "dotnet Ordering.Sig…"   2 hours ago         Up 4 minutes        0.0.0.0:5112->80/tcp                                                                         src_ordering-signalrhub_1
aa8f1b97e2d9        eshop/mobileshoppingagg:linux-latest          "dotnet Mobile.Shopp…"   2 hours ago         Up 4 minutes        0.0.0.0:5120->80/tcp                                                                         src_mobileshoppingagg_1
fce1a341f140        eshop/webshoppingagg:linux-latest             "dotnet Web.Shopping…"   2 hours ago         Up 4 minutes        0.0.0.0:5121->80/tcp                                                                         src_webshoppingagg_1
6acf199434c5        eshop/webhooks.client:linux-latest            "dotnet WebhookClien…"   2 hours ago         Up 4 minutes        443/tcp, 0.0.0.0:5114->80/tcp                                                                src_webhooks-client_1
dc010fc35544        eshop/basket.api:linux-latest                 "dotnet Basket.API.d…"   2 hours ago         Up 4 minutes        0.0.0.0:5103->80/tcp, 0.0.0.0:9103->81/tcp                                                   src_basket-api_1
5d25597f528c        eshop/marketing.api:linux-latest              "dotnet Marketing.AP…"   2 hours ago         Up 4 minutes        0.0.0.0:5110->80/tcp                                                                         src_marketing-api_1
322d35948e4e        eshop/webhooks.api:linux-latest               "dotnet Webhooks.API…"   2 hours ago         Up 4 minutes        0.0.0.0:5113->80/tcp                                                                         src_webhooks-api_1
42c2558246e7        eshop/catalog.api:linux-latest                "dotnet Catalog.API.…"   2 hours ago         Up 4 minutes        443/tcp, 0.0.0.0:5101->80/tcp, 0.0.0.0:9101->81/tcp                                          src_catalog-api_1
63271c568726        eshop/identity.api:linux-latest               "dotnet Identity.API…"   2 hours ago         Up 4 minutes        0.0.0.0:5105->80/tcp                                                                         src_identity-api_1
e721e25786b4        eshop/ordering.api:linux-latest               "dotnet Ordering.API…"   2 hours ago         Up 4 minutes        0.0.0.0:5102->80/tcp, 0.0.0.0:9102->81/tcp                                                   src_ordering-api_1
9309226e31ae        eshop/webspa:linux-latest                     "dotnet WebSPA.dll"      2 hours ago         Up 4 minutes        0.0.0.0:5104->80/tcp                                                                         src_webspa_1
e4c143ad8298        eshop/payment.api:linux-latest                "dotnet Payment.API.…"   2 days ago          Up 4 minutes        0.0.0.0:5108->80/tcp                                                                         src_payment-api_1
73ad8cc7340e        eshop/ordering.backgroundtasks:linux-latest   "dotnet Ordering.Bac…"   2 days ago          Up 4 minutes        0.0.0.0:5111->80/tcp                                                                         src_ordering-backgroundtasks_1
0e366dbae410        envoyproxy/envoy:v1.11.1                      "/docker-entrypoint.…"   2 days ago          Up 4 minutes        10000/tcp, 0.0.0.0:5201->80/tcp, 0.0.0.0:15201->8001/tcp                                     src_mobilemarketingapigw_1
a362e9e7b771        datalust/seq:latest                           "/run.sh"                2 days ago          Up 4 minutes        5341/tcp, 0.0.0.0:5340->80/tcp                                                               src_seq_1
f5cc75781730        rabbitmq:3-management-alpine                  "docker-entrypoint.s…"   2 days ago          Up 4 minutes        4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   src_rabbitmq_1
ed8ba3e8c41d        redis:alpine                                  "docker-entrypoint.s…"   2 days ago          Up 4 minutes        0.0.0.0:6379->6379/tcp                                                                       src_basketdata_1
956838a9374c        envoyproxy/envoy:v1.11.1                      "/docker-entrypoint.…"   2 days ago          Up 4 minutes        10000/tcp, 0.0.0.0:5202->80/tcp, 0.0.0.0:15202->8001/tcp                                     src_webshoppingapigw_1
5713c0a47cda        envoyproxy/envoy:v1.11.1                      "/docker-entrypoint.…"   2 days ago          Up 4 minutes        10000/tcp, 0.0.0.0:5200->80/tcp, 0.0.0.0:15200->8001/tcp                                     src_mobileshoppingapigw_1
e58f53148e88        mcr.microsoft.com/mssql/server:2017-latest    "/opt/mssql/bin/nonr…"   2 days ago          Up 4 minutes        0.0.0.0:5433->1433/tcp                                                                       src_sqldata_1
7c80b31d7754        eshop/webstatus:linux-latest                  "dotnet WebStatus.dll"   2 days ago          Up 4 minutes        0.0.0.0:5107->80/tcp                                                                         src_webstatus_1
52548ebf3016        envoyproxy/envoy:v1.11.1                      "/docker-entrypoint.…"   2 days ago          Up 4 minutes        10000/tcp, 0.0.0.0:5203->80/tcp, 0.0.0.0:15203->8001/tcp                                     src_webmarketingapigw_1

**Comment by dereklew** [comment]
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.269+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.304+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.306+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.309+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"f09c6a2c101f"}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.0","gitVersion":"563487e100c4215e2dce98d0af2a6a5a2d67c5cf","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"x86_64","target_arch":"x86_64"}}}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.309+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.309+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.317+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.317+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:15.317+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3471M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:21.765+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:21.765+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"95: Operation not supported"}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:21.765+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":1100}}
[34;1mnosqldata_1                 |[0m {"t":{"$date":"2020-08-04T16:24:21.765+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}

**Comment by sughosneo** [comment]
Thanks @dereklew for the details. Yes, mongodb docker container is not up and running and that's the reason Location.API is throwing that connection related exception.

If you looking at the below trace, it's related storage exception. I guess it could be something related to volume mount for no-sql data store.

```powershell
"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine"
```

1) Are you able to run the mongodb container manually ? For e.g : using `docker run`
2) Are you able to see *eshop-nosqldata* related volume data while you run `docker volume ls` ?
3) Can you delete older docker images and volumes and try to start it again ?

**Comment by dereklew** [comment]
Thanks @sughosneo , this command to remove the volume, solved the problem.  docker volume rm $(docker volume ls -q)

**Comment by sughosneo** [comment]
Great ! Thanks for the update @dereklew.  Closing this issue as of now.
