### ISSUE TITLE
ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not se

### ISSUE THREAD

**Issue by robpahl** [dotnet-architecture/eShopOnContainers#238]
Building the 'eShopOnContainers - ServicesAndWebApps'
the following variables are reported empty, defaulting to a blank strings

ESHOP_AZURE_STORAGE_CATALOG_NAME
ESHOP_AZURE_STORAGE_CATALOG_KEY
ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI
ESHOP_AZURE_STORAGE_MARKETING_NAME
ESHOP_AZURE_STORAGE_MARKETING_KEY

resulting in a PrepareForLaunch task fail:
I'm Probably missed/omitted something but I do not figure out what.

**Comment by CESARDELATORRE** [comment]
Those env vars are only needed when Deploying to Azure the opt-in elements for "production" environments.
When deploying to a dev environment with just Docker for Windows in your dev Machine, we have F5 experience, so no need of anything related to Azure. What branch are you using? Use eShopOnContainers/DEV. 
Not sure why you are getting that error now.. it should not happen in a dev environment..

**Comment by robpahl** [comment]
Hmmm. just downloaded the .zip today and tried to run straight up.  Could it be related to me running in nested Virtualization mode,. 'Docker in a VM under Hyper-v'?

**Comment by robpahl** [comment]
the 'eShopOnContainers-dev' is what I have.

**Comment by CESARDELATORRE** [comment]
Could be. Docker for Windows uses Hyper-V so a nested virtualization mode could be problematic. We don't use and have not tested Docker for Windows in nested virtualization mode, so we don't support that environment. Might be possible that Docker doesn't support that environment, not sure.

**Comment by CESARDELATORRE** [comment]
Closing, for now, as it looks an environment issue when using nested virtualization.

**Comment by infofromca** [comment]
@CESARDELATORRE pls reopen it as this happen for me too.
vs 2017 pro
master 
load the eShopOnContainers-ServicesAndWebApps.sln
clean
got this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "CleanWorkspace" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\main.py", line 525, in kill
  File "compose\project.py", line 278, in kill
  File "compose\project.py", line 500, in containers
  File "compose\project.py", line 491, in _labeled_containers
  File "site-packages\docker\api\container.py", line 189, in containers
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose.

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.DotNet.Docker.CommandLineClientException: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\main.py", line 525, in kill
  File "compose\project.py", line 278, in kill
  File "compose\project.py", line 500, in containers
  File "compose\project.py", line 491, in _labeled_containers
  File "site-packages\docker\api\container.py", line 189, in containers
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerComposeClient.<DownAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerWorkspace.<CleanWorkspaceAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets	208

**Comment by CESARDELATORRE** [comment]
Are you using nested virtualization?. The current supported environment is a local machine (PC) with Docker for Windows or Mac installed. See: https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements 
Do you have Docker set up to use the by default Linux Docker host setup automatically as the HyperV Linux VM (so, I mean, Docker not configured for Windows Containers which is not the default)
Did you follow the setup procedure step by step? : https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment
All the "ESHOP_AZURE_XXX" are only needed when using databases and services from Azure. For a simpler deployment to a local dev machine with Docker for Windows or Docker for Mac, you don't need any of those variables so the error might be caused for something related to the environment.
