### ISSUE TITLE
Need guidance to run unit/integration/functional/load tests

### ISSUE THREAD

**Issue by LiangZugeng** [dotnet-architecture/eShopOnContainers#419]
This is a great reference project, it not only demos how the application code should be written and how the app architecture should be designed, it also demos how the tests are automated, I actually found the design/implementation of automated test cases helps me more.

If there is a wiki article explaining how to setup for automated tests, that will be great. I had no problems running unit tests (dotnet restore >> dotnet test), however for integration/functional/load tests I failed to run them by using just dotnet test command.

@CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
When running tests which are consuming/using the microservices/containers you need to run the containers first, either from VS or by starting the app with "docker-compose up".
Not sure if that was your problem as you are not providing the errors you got.

**Comment by LiangZugeng** [comment]
Thanks for your reply @CESARDELATORRE , I just tried to run integration tests after running the containers (I started them in VS2017), but still failed to do so on both Windows and Mac. I verified the running of all containers by successfully accessing to http://localhost:5100 and submitting a order.

[12/5/2017 12:03:31 AM Error] [xUnit.net 00:00:01.6133639]     IntegrationTests.Services.Basket.BasketScenarios.Get_basket_and_response_ok_status_code [FAIL]
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6147969]       Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IEventBus (DelegateActivator), Services = [Microsoft.eShopOnContainers.BuildingBlocks.EventBus.Abstractions.IEventBus], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> String reference not set to an instance of a String.
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6149746]       Parameter name: s (See inner exception for details.)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6150177]       ---- System.ArgumentNullException : String reference not set to an instance of a String.
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6150432]       Parameter name: s
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6161488]       Stack Trace:
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6173811]            at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6175257]            at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6175754]            at Autofac.Core.Resolving.InstanceLookup.Execute()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6176366]            at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6177604]            at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6178272]            at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6179116]            at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6179700]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6180549]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6181282]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\src\Services\Basket\Basket.API\Startup.cs(302,0): at Microsoft.eShopOnContainers.Services.Basket.API.Startup.ConfigureEventBus(IApplicationBuilder app)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6185460]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\src\Services\Basket\Basket.API\Startup.cs(206,0): at Microsoft.eShopOnContainers.Services.Basket.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6186791]         --- End of stack trace from previous location where exception was thrown ---
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6187306]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6187812]            at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6188368]            at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6189342]            at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6190214]            at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6190720]            at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6191276]            at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6191749]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\test\Services\IntegrationTests\Services\Basket\BasketScenarioBase.cs(18,0): at IntegrationTests.Services.Basket.BasketScenarioBase.CreateServer()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6192913]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\test\Services\IntegrationTests\Services\Basket\BasketScenarios.cs(32,0): at IntegrationTests.Services.Basket.BasketScenarios.<Get_basket_and_response_ok_status_code>d__1.MoveNext()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6193516]         --- End of stack trace from previous location where exception was thrown ---
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6194040]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6194485]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6194893]         --- End of stack trace from previous location where exception was thrown ---
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6195315]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6195696]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6196099]         --- End of stack trace from previous location where exception was thrown ---
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6196614]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6197120]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6197486]         ----- Inner Stack Trace -----
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6197764]            at System.Text.Encoding.GetBytes(String s)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6198223]            at RabbitMQ.Client.Impl.WireFormatting.WriteShortstr(NetworkBinaryWriter writer, String val)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6198696]            at RabbitMQ.Client.Framing.Impl.QueueDeclare.WriteArgumentsTo(MethodArgumentWriter writer)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6199114]            at RabbitMQ.Client.Impl.Command.TransmitAsSingleFrame(Int32 channelNumber, Connection connection)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6200143]            at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6200677]            at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6201242]            at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6202175]            at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6203659]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\EventBusRabbitMQ.cs(173,0): at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ.CreateConsumerChannel()
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6204489]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\EventBusRabbitMQ.cs(41,0): at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ..ctor(IRabbitMQPersistentConnection persistentConnection, ILogger`1 logger, ILifetimeScope autofac, IEventBusSubscriptionsManager subsManager, String queueName, Int32 retryCount)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6205611]         C:\Users\lzg\Documents\Projects\Learning\eShopOnContainers\src\Services\Basket\Basket.API\Startup.cs(290,0): at Microsoft.eShopOnContainers.Services.Basket.API.Startup.<>c__DisplayClass9_0.<RegisterEventBus>b__1(IServiceProvider sp)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6206715]            at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6207202]            at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
[12/5/2017 12:03:31 AM Informational] [xUnit.net 00:00:01.6354963]   Finished:    FunctionalTests
[12/5/2017 12:03:32 AM Informational] ========== Run test finished: 1 run (0:00:02.4764396) ==========

**Comment by LiangZugeng** [comment]
@CESARDELATORRE still had problems running integration/functional tests even when all containers are up and running, could you please kindly let me know where and how you guys run integration/functional tests, for example maybe you only run integration/functional tests in the cloud testing machine but never run it on dev machine, if they are OK to run on dev machine what the instructions are to properly run them.

Also may I know the approximate coverage of integration/function tests for the whole project?

The reason I asked the details is that we are planning the investment on test automations (yeap we are not doing any test automation) so I'm studying the automated test cases (the design, implementation etc) in eShopOnContains to get me started on writing good test cases for micro-service applications. Thank you very much in advance.

**Comment by ramonTC** [comment]
Hi Liang,

It's actually not necessary to run all the containers.
Since we are using TestServer for our Integration/Functional tests you only have to run the infrastructure services (sql, redis cache, ...). Just execute the following command to keep them up & running:

**docker-compose -f docker-compose-external.yml -f docker-compose-external.override.yml up**

Please check them out again as we have fixed some issues related to integration/functional tests.

Thx.

**Comment by LiangZugeng** [comment]
@ramonTC thank you for your instruction, I can now successfully run the integration tests after running the infrastructure services, since I'm running them on MacOS I changed all ScenarioBase classes to use linux/unit style of file paths like follows (originally it uses Windows style file paths):

```
webHostBuilder.UseContentRoot(Directory.GetCurrentDirectory() + "/Services/Basket");
```

However I still got the following error.

------
Starting test execution, please wait...
[xUnit.net 00:00:00.9970030]   Discovering: FunctionalTests
[xUnit.net 00:00:01.0740390]   Discovered:  FunctionalTests
[xUnit.net 00:00:01.0795730]   Starting:    FunctionalTests

...

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/james/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (0ms) [Parameters=[@p0='?', @p1='?' (Size = 4000), @p2='?'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [ordering].[requests] ([Id], [Name], [Time])
      VALUES (@p0, @p1, @p2);
info: Ordering.API.Infrastructure.Behaviors.LoggingBehavior[0]
      Handling CancelOrderCommand
info: Ordering.API.Infrastructure.Behaviors.LoggingBehavior[0]
      Handling IdentifiedCommand`2
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (1ms) [Parameters=[@__get_Item_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [e].[Id], [e].[Name], [e].[Time]
      FROM [ordering].[requests] AS [e]
      WHERE [e].[Id] = @__get_Item_0
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (0ms) [Parameters=[@__get_Item_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [e].[Id], [e].[Name], [e].[Time]
      FROM [ordering].[requests] AS [e]
      WHERE [e].[Id] = @__get_Item_0
info: Microsoft.EntityFrameworkCore.Database.Command[200101]
      Executed DbCommand (0ms) [Parameters=[@p0='?', @p1='?' (Size = 4000), @p2='?'], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [ordering].[requests] ([Id], [Name], [Time])
      VALUES (@p0, @p1, @p2);
info: Ordering.API.Infrastructure.Behaviors.LoggingBehavior[0]
      Handling CreateOrderCommand
The active test run was aborted. Reason: om previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.LoggingBehavior`2.<Handle>d__2.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/Services/Ordering/Ordering.API/Application/Behaviors/LoggingBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.eShopOnContainers.Services.Ordering.API.Application.Commands.IdentifiedCommandHandler`2.<Handle>d__4.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/Services/Ordering/Ordering.API/Application/Commands/IdentifiedCommandHandler.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.ValidatorBehavior`2.<Handle>d__2.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/Services/Ordering/Ordering.API/Application/Behaviors/ValidatorBehavior.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.LoggingBehavior`2.<Handle>d__2.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/Services/Ordering/Ordering.API/Application/Behaviors/LoggingBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Application.IntegrationEvents.EventHandling.UserCheckoutAcceptedIntegrationEventHandler.<Handle>d__4.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/UserCheckoutAcceptedIntegrationEventHandler.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ.<ProcessEvent>d__19.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ.<<CreateConsumerChannel>b__18_0>d.MoveNext() in /Users/james/Projects/Learning/eShopOnContainers/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Failed.
Test execution time: 5.9361 Seconds
---------

I spent some time trying to solve the issue and ended up with commenting out Send_Checkout_basket_and_response_ok_status_code test case in BasketScenarios.cs, after that I got all 31 test cases passed.

I assume you are not running the integration test cases on MacOS due to the Windows file path style, can you find a Mac to run them and see if you can reproduce the issue I encountered (I use a MBP 16GB Mem 1TB SSD with MacOS 10.13.2). I will run the integration tests on Windows machine tomorrow and see if it's a Mac-only issue.

I may submit a PR to fix the file path style issue by using Path.Combine for path concatenation.

**Comment by mvelosop** [comment]
Hi @LiangZugeng, you might want to take a look at PR #526 and test it in you Mac to check if that takes tests to the end.

**Comment by mvelosop** [comment]
Closing because PR #526 seems to have fixed this issue.
