### ISSUE TITLE
I got the Docker error after first load of the solution

### ISSUE THREAD

**Issue by saqw3r** [dotnet-architecture/eShopOnContainers#460]
![image](https://user-images.githubusercontent.com/8653893/34676443-7adf74ea-f495-11e7-961a-88ecf6d45911.png)
This is an error I got after the first load of the solution (eShopOnContainers-ServicesAndWebApps.sln)
Environment: Windows 10, Visual Studio Enterprise 2017 Preview v.15.6.0 Preview 1.1
Docker: version 17.10.0-ce, build f4ffd25
Branch: dev

**Comment by saqw3r** [comment]
Execution of a command "Docker-compose build" does lead to the successful result - it returns a message: "ERROR: Version in ".\docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/"

**Comment by CESARDELATORRE** [comment]
You need to have the last version of Docker installed. If you cannot, you just need to switch the version from 3.4 to 3.3 in all the Docker-compose files.

**Comment by CESARDELATORRE** [comment]
Also, it could be related to the VS Preview version. We’re using VS 2017 15.5.2, release.

**Comment by saqw3r** [comment]
The problem is that I do have the latest. I installed it yesterday on my quite fresh Windows. I had a command "Docker-compose build" run from Console. That's why I don't think it is related to IDE.

**Comment by CESARDELATORRE** [comment]
@saqw3r But I see you are using Visual Studio Enterprise 2017 Preview v.15.6.0 **Preview** 1.1. 
Please, do use the RTM/release version VS2017 v 15.5.2 or later, but in RTM/release, not Preview. We haven't tested eShopOnContainers with that Preview version.
If it is related to a Docker's environment issue, try reinstalling Docker which should be quick and don't forget to assing at least 4GB or memory to Docker, 3 CPUs and share the Drives in Docker, as well.

**Comment by alfogo** [comment]
I got this error a while ago. On my case it was I was running Docker for Windows instead of Linux. After switching I could build the project

**Comment by CESARDELATORRE** [comment]
Right, please, check that out. That is a basic requirement since the Docker-compose being used by the solution target Linux Containers which is the by default option in VS.
@alfogo thanks! :)

**Comment by saqw3r** [comment]
After downgrading version of docker-compose file in commit 08a5eeea71e98e5fbb55dfb645294dd245da4aa3 this error went out. However I see a next traceback:
_Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 249, in build
  File "compose\project.py", line 343, in build
  File "compose\service.py", line 918, in build
  File "site-packages\docker\api\build.py", line 246, in build
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 185, in _post
  File "site-packages\requests\sessions.py", line 522, in post
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose_

**Comment by CESARDELATORRE** [comment]
Can you confirm that you are running Docker for Windows targeting Linux containers? (Not setting Docker for Windows on Windows Containers) - 
If you are targeting Linux containers from Docker for windows, can you try a different machine? Looks like it is related to that specific environment.

**Comment by saqw3r** [comment]
The problem was, that service com.docker.service somehow was not registered in my Windows Services. After reinstallation of Docker, the issue run away. Thanks, guys! Sorry, that I bothered you and took your time.
