### ISSUE TITLE
Debug in VS2017 Error

### ISSUE THREAD

**Issue by chewel611** [dotnet-architecture/eShopOnContainers#461]
docker-compose  -f "E:\项目代码\eShopOnContainers-dev\docker-compose.yml" -f "E:\项目代码\eShopOnContainers-dev\docker-compose.override.yml" -p dockercompose1228189227022563607 config
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 115, in perform_command
  File "compose\cli\main.py", line 299, in config
  File "compose\cli\command.py", line 44, in get_config_from_options
  File "compose\cli\command.py", line 57, in get_config_path_from_options
  File "compose\cli\command.py", line 53, in unicode_paths
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 3: invalid continuation byte
Failed to execute script docker-compose

**Comment by CESARDELATORRE** [comment]
Can you provide the environment you have? OS versions, Docker version, etc. language?
Looks like an issue related to language/localized version?

**Comment by mvelosop** [comment]
Closing this issue as it became stale!
