### ISSUE TITLE
Can not run all test together.

### ISSUE THREAD

**Issue by raboud** [dotnet-architecture/eShopOnContainers#497]
when i select all test and run Xunit aborts part way thru.

found the first issue

ProductPriceChangedIntegrationEventHandler.UpdatePriceInBasketItems
is in the int.Parse that one is a pretty easy fix

the other one seems to be cause by

Send_Checkout_basket_and_response_ok_status_code

[2/1/2018 10:19:21 AM Warning] Ignoring the load test contained in file 'f:\code\github\eshoponcontainers\test\services\loadtest\basket.loadtest' as it is not supported in Unit Test Explorer. To run this test, open the load test file and run it from its editor. For more information see: http://go.microsoft.com/fwlink/?LinkID=236838&clcid=0x409
[2/1/2018 10:19:21 AM Warning] Ignoring the load test contained in file 'f:\code\github\eshoponcontainers\test\services\loadtest\campaigns.loadtest' as it is not supported in Unit Test Explorer. To run this test, open the load test file and run it from its editor. For more information see: http://go.microsoft.com/fwlink/?LinkID=236838&clcid=0x409
[2/1/2018 10:19:21 AM Warning] Ignoring the load test contained in file 'f:\code\github\eshoponcontainers\test\services\loadtest\catalog.loadtest' as it is not supported in Unit Test Explorer. To run this test, open the load test file and run it from its editor. For more information see: http://go.microsoft.com/fwlink/?LinkID=236838&clcid=0x409
[2/1/2018 10:19:21 AM Warning] Ignoring the load test contained in file 'f:\code\github\eshoponcontainers\test\services\loadtest\locations.loadtest' as it is not supported in Unit Test Explorer. To run this test, open the load test file and run it from its editor. For more information see: http://go.microsoft.com/fwlink/?LinkID=236838&clcid=0x409
[2/1/2018 10:19:21 AM Warning] Ignoring the load test contained in file 'f:\code\github\eshoponcontainers\test\services\loadtest\orderproducts.loadtest' as it is not supported in Unit Test Explorer. To run this test, open the load test file and run it from its editor. For more information see: http://go.microsoft.com/fwlink/?LinkID=236838&clcid=0x409
[2/1/2018 10:19:21 AM Informational] ------ Run test started ------
[2/1/2018 10:19:24 AM Informational] [xUnit.net 00:00:01.2349836] Received 3 results from 3 requests
[2/1/2018 10:19:24 AM Informational] [xUnit.net 00:00:01.2620100]   Starting:    FunctionalTests
[2/1/2018 10:19:27 AM Informational] [xUnit.net 00:00:04.6462439]   Finished:    FunctionalTests
[2/1/2018 10:19:29 AM Informational] [xUnit.net 00:00:01.0723174] Received 32 results from 32 requests
[2/1/2018 10:19:29 AM Informational] [xUnit.net 00:00:01.1005810]   Starting:    FunctionalTests
[2/1/2018 10:19:40 AM Error] The active test run was aborted. Reason: \ValidatorBehavior.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.LoggingBehavior`2.<Handle>d__2.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\Services\Ordering\Ordering.API\Application\Behaviors\LoggingBehavior.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.eShopOnContainers.Services.Ordering.API.Application.Commands.IdentifiedCommandHandler`2.<Handle>d__4.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\Services\Ordering\Ordering.API\Application\Commands\IdentifiedCommandHandler.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.ValidatorBehavior`2.<Handle>d__2.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\Services\Ordering\Ordering.API\Application\Behaviors\ValidatorBehavior.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Infrastructure.Behaviors.LoggingBehavior`2.<Handle>d__2.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\Services\Ordering\Ordering.API\Application\Behaviors\LoggingBehavior.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ordering.API.Application.IntegrationEvents.EventHandling.UserCheckoutAcceptedIntegrationEventHandler.<Handle>d__4.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\Services\Ordering\Ordering.API\Application\IntegrationEvents\EventHandling\UserCheckoutAcceptedIntegrationEventHandler.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ.<ProcessEvent>d__19.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\EventBusRabbitMQ.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.EventBusRabbitMQ.<>c__DisplayClass18_0.<<CreateConsumerChannel>b__0>d.MoveNext() in F:\Code\GitHub\eshopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\EventBusRabbitMQ.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[2/1/2018 10:19:41 AM Informational] [xUnit.net 00:00:00.9718006] Received 38 results from 38 requests
[2/1/2018 10:19:41 AM Informational] [xUnit.net 00:00:00.9971076]   Starting:    UnitTest
[2/1/2018 10:19:42 AM Informational] [xUnit.net 00:00:01.5156875]   Finished:    UnitTest
[2/1/2018 10:19:42 AM Informational] ========== Run test finished: 55 run (0:00:20.3323803) ==========

**Comment by mvelosop** [comment]
Hi @raboud, thanks for the information, I was investigating the error and found the origin of the int.Parse error in line 72 of RedisBasketRepositoryTests.cs, this is the fix:

![devenv_2018-02-26_20-11-45](https://user-images.githubusercontent.com/7357806/36693126-3074e278-1b32-11e8-896d-259f64e8ee08.png)

After fixing that, all three functional tests completed successfully.

![devenv_2018-02-26_20-23-06](https://user-images.githubusercontent.com/7357806/36693300-cb2ab752-1b32-11e8-94fb-d45f43e10a22.png)

I don't get any more problems (with Functional tests), at least as of commit 68d07830 from FEB-19-2018

Could you please check if that solves your problems too?

TIA

**Comment by raboud** [comment]
I already put in a pull request to fix that bug.

but when i try to run all the test (70+) is where it will die somewhere and not run all the test.

The offending test seems to be Send_Checkout_basket_and_response_ok_status_code.

When i include that test in the selected tests only about 50+ test run ...no reported failures but exceptions in the output window. (Send_Checkout_basket_and_response_ok_status_code passes)
The active test run was aborted. Reason: Unhandled Exception: Ordering.Domain.Exceptions

Unselecting that test and running I get 75 pass no failures and no exceptions in the output window.

All of these results are with the int.Parse bug fix inplace.

**Comment by mvelosop** [comment]
I think your approach to the fix is better than what I initially did, as the BasketItem.ProductId is a string property, so it makes more sense make the where clause the way you suggested. I just requested some minor changes to PR #499.

Will keep looking at the other errors, I also get them.

Thanks for your input.

**Comment by mvelosop** [comment]
We are getting close @raboud! I found a workaround and created PR #526, it's just a minor change, so it would be great if you could verify if that fixes the issue for you.

It's just a workaroud because the real bug is that a failing validation aborts the test run, but will continue tomorrow. enough for today!

**Comment by raboud** [comment]
@mvelosop I have a theory

my theory is we are running the test wrong.

we need to run with a test fixture such that we have One of each of the servers running not one copy per test. Multiple copies are getting of the servers are getting the events and acting on them but they don't have the correct data.

This is just a theory.

**Comment by raboud** [comment]
@mvelosop do we have any test that actually test out how invalid data is handled?

**Comment by mvelosop** [comment]
@raboud I'm just starting with this app, getting to know the details, so I may be wrong, but there doesn't seem to be a test for validation failures. It should've handled the aborting test, although it could be a MediatR bug, have to delve into this deeper.

I'm not sure what you mean with your theory.

Do you mean not using(var server = CreateServer()) but starting the scenario from the real server running in a container?

**Comment by CESARDELATORRE** [comment]
Just so you know, there are many scenarios in the app that might not have Unite Tests or Integration Tests related. That is an area that could very much improved with PRs from the community.
In fact, I'm leaning about splitting the tests in multiple test projects each one for a different microservice, so even the test projects would be autonomous.
I don't really like to have "monolithic" test projects in a microservice based application.
But, as I said, that is a priority that could be helped with PRs from the community. :)

**Comment by raboud** [comment]
@mvelosop woo hoo found the issue

run the Send_Checkout_basket_and_response_ok_status_code there is no OrderApiServer running.
run it with all the test running and you an OrderApiServer running which is handling MediaR messages.

OrderApi gets the CreateOrderCommand tries to validate - Validate fails throws an exception that is never caught.

the problem is in the IdentifiedCommandHandler<T, R>::Handle method

`var result = await _mediator.Send(message.Command);
return result;`

needs to be 

`				try
				{
					var result = await _mediator.Send(message.Command);
					return result;
				}
				catch (Exception e)
				{
					return default(R);
				}`

by running all the test we just triggered another bug to appear like magic. HEHE

unfortnately the basketapi will never know the order creation failed

Ill have to create a new branch for the PR as the branch I'm working in has to much going on to PR from here.

**Comment by mvelosop** [comment]
@raboud, I'm not sure this is the right way to handle validation failure, I think it should be in MediatR's behaviour pipeline, because it doesn't seem right that a validation failure, or any other exception for that matter, takes down the whole pipeline.

**Comment by mvelosop** [comment]
Hi @raboud, building from your suggestion maybe returning something like an **`EventResult<TResponse>`** instead of just **`TResponse`**, where EventResult would have a Succeded, Messages and Value properties, where Value would be TResponse.

Then we could check if the event publication was successful and do something in case it was not.

**Comment by mvelosop** [comment]
Reviewing this issue with @CESARDELATORRE, the conclusion is that, for the time being, your approach is the chosen path. 

In order to not simply ignore validation errors (and any other in the pipeline) it would be good to log both, the exception in the catch block of #529 and also log the validation error messages in ValidatorBehavior.

**Comment by mvelosop** [comment]
Closing as this this issue was partially handled with PR #529.
