### ISSUE TITLE
[Local environment issue] Failed to execute script docker-compose

### ISSUE THREAD

**Issue by Kaidanov** [dotnet-architecture/eShopOnContainers#510]
Docker is running well , but the compose is getting stack.. 
I want to run WebSPA 
2 days of hair pulling..
Any advise? I really want to play with this architecture but the time it takes to make it work if tremendous 

![image](https://user-images.githubusercontent.com/164266/36072854-db2c19ac-0f2f-11e8-9154-25b7f6ed63f9.png)
![image](https://user-images.githubusercontent.com/164266/36072856-e7b1afe8-0f2f-11e8-8efd-9a1cc0d88587.png)
![image](https://user-images.githubusercontent.com/164266/36072877-1dbbbb06-0f30-11e8-9792-d6ec219dfd28.png)
![image](https://user-images.githubusercontent.com/164266/36072886-2c03157e-0f30-11e8-988b-01d2b607d2e8.png)

```
PS C:\WINDOWS\system32> docker --version
Docker version 17.12.0-ce, build c97c6d6
PS C:\WINDOWS\system32> docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true


PS C:\dev\eShopOnContainers> Docker-compose up
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Creating network "eshoponcontainers_default" with the default driver
Pulling basket.data (redis:alpine)...
alpine: Pulling from library/redis
ff3a5c916c92: Pull complete
aae70a2e6027: Pull complete
87c655da471c: Pull complete
a0bd51ac7350: Pull complete
755565c3ea2b: Pull complete
8bf100ea488d: Pull complete
Digest: sha256:95a7b91d1e96fa2e4579f439137e5642d3c58d5f8d063d6cea09426d56a22ec0
Status: Downloaded newer image for redis:alpine
Pulling nosql.data (mongo:latest)...
latest: Pulling from library/mongo
c4bb02b17bb4: Pull complete
3f58e3bb3be4: Pull complete
a229fb575a6e: Pull complete
8f5ddc533743: Pull complete
5e9d2af6e206: Pull complete
3b6c28c0235b: Pull complete
f6688308f715: Pull complete
c07c56202c1a: Pull complete
8cd9b5a8a428: Pull complete
fdf24480e182: Pull complete
Digest: sha256:878b76e5834f37da98096296f4147f6ca4d94b1a9187986e9d6e59756e7ce865
Status: Downloaded newer image for mongo:latest
Pulling rabbitmq (rabbitmq:3-management-alpine)...
3-management-alpine: Pulling from library/rabbitmq
ff3a5c916c92: Already exists
5387f4b4c52b: Pull complete
dba8c403a5b6: Pull complete
4258fc50c523: Pull complete
f0097dfba081: Pull complete
811b1938a3e7: Pull complete
d76f344cd737: Pull complete
0750d740f1e1: Pull complete
0b25aa17368d: Pull complete
3be63f09bb62: Pull complete
9cc4bbd7c081: Pull complete
Digest: sha256:2edd7eb1a8b19eb30feaee109324017f4a9e1677122faf33c1403340fa9a99cd
Status: Downloaded newer image for rabbitmq:3-management-alpine
Pulling sql.data (microsoft/mssql-server-linux:2017-latest)...
2017-latest: Pulling from microsoft/mssql-server-linux
f6fa9a861b90: Pull complete
da7318603015: Pull complete
6a8bd10c9278: Pull complete
d5a40291440f: Pull complete
bbdd8a83c0f1: Pull complete
3a52205d40a6: Pull complete
6192691706e8: Pull complete
1a658a9035fb: Pull complete
827975ce0c02: Pull complete
ea7199b7fbb6: Pull complete
Digest: sha256:fa1265cae3447320542cd0d1da160988aeffe5d2ae602a84336ddbd069e2b4ee
Status: Downloaded newer image for microsoft/mssql-server-linux:2017-latest
Building basket.api
Step 1/15 : FROM microsoft/aspnetcore:2.0.3 AS base
 ---> 7f83f41eee6d
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> c52a5b913ae0
Step 3/15 : EXPOSE 80
 ---> Using cache
 ---> 0c773cd8f37f

Step 4/15 : FROM microsoft/aspnetcore-build:2.0 AS build
 ---> 6105426f13e9
Step 5/15 : WORKDIR /src
 ---> Using cache
 ---> 4513e633d04d
Step 6/15 : COPY . .
 ---> Using cache
 ---> 66e1a34dfe17
Step 7/15 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> af1229934724
Step 8/15 : WORKDIR /src/src/Services/Basket/Basket.API
Removing intermediate container 02a0104a816f
 ---> 0105297b6aea
Step 9/15 : RUN dotnet build --no-restore -c Release -o /app
 ---> Running in 970d8e54f5b7
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /app/EventBus.dll
  EventBusRabbitMQ -> /app/EventBusRabbitMQ.dll
  EventBusServiceBus -> /app/EventBusServiceBus.dll
  Microsoft.Extensions.HealthChecks -> /app/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /app/Microsoft.AspNetCore.HealthChecks.dll
  Basket.API -> /app/Basket.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:35.50
Removing intermediate container 970d8e54f5b7
 ---> 0cfa97934ed1

Step 10/15 : FROM build AS publish
 ---> 0cfa97934ed1
Step 11/15 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in 30ff1bc6a3a5
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /src/src/BuildingBlocks/EventBus/EventBus/bin/Release/netstandard2.0/EventBus.dll
  EventBusRabbitMQ -> /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/netstandard2.0/EventBusRabbitMQ.dll
  EventBusServiceBus -> /src/src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/netstandard2.0/EventBusServiceBus.dll
  Microsoft.Extensions.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/bin/Release/netstandard2.0/Microsoft.AspNetCore.HealthChecks.dll
  Basket.API -> /src/src/Services/Basket/Basket.API/bin/Release/netcoreapp2.0/Basket.API.dll
  Basket.API -> /app/
Removing intermediate container 30ff1bc6a3a5
 ---> 60a9ea19094b

Step 12/15 : FROM base AS final
 ---> 0c773cd8f37f
Step 13/15 : WORKDIR /app
 ---> Using cache
 ---> 313e17ef950b
Step 14/15 : COPY --from=publish /app .
 ---> 33f2ef7150e5
Step 15/15 : ENTRYPOINT ["dotnet", "Basket.API.dll"]
 ---> Running in 9b75663f3dcc
Removing intermediate container 9b75663f3dcc
 ---> ab8daca3c958

Successfully built ab8daca3c958
Successfully tagged eshop/basket.api:latest
WARNING: Image for service basket.api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building marketing.api
Step 1/15 : FROM microsoft/aspnetcore:2.0.3 AS base
 ---> 7f83f41eee6d
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> c52a5b913ae0
Step 3/15 : EXPOSE 80
 ---> Using cache
 ---> 0c773cd8f37f

Step 4/15 : FROM microsoft/aspnetcore-build:2.0 AS build
 ---> 6105426f13e9
Step 5/15 : WORKDIR /src
 ---> Using cache
 ---> 4513e633d04d
Step 6/15 : COPY . .
 ---> Using cache
 ---> 66e1a34dfe17
Step 7/15 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> af1229934724
Step 8/15 : WORKDIR /src/src/Services/Marketing/Marketing.API
Removing intermediate container 537c0b14a0cb
 ---> ed2d1f82b1ef
Step 9/15 : RUN dotnet build --no-restore -c Release -o /app
 ---> Running in 0abc4a304b7b
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /app/EventBus.dll
  EventBusRabbitMQ -> /app/EventBusRabbitMQ.dll
  Microsoft.Extensions.HealthChecks -> /app/Microsoft.Extensions.HealthChecks.dll
  Microsoft.Extensions.HealthChecks.AzureStorage -> /app/Microsoft.Extensions.HealthChecks.AzureStorage.dll
  Microsoft.AspNetCore.HealthChecks -> /app/Microsoft.AspNetCore.HealthChecks.dll
  EventBusServiceBus -> /app/EventBusServiceBus.dll
  WebHost.Customization -> /app/WebHost.Customization.dll
  Marketing.API -> /app/Marketing.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:38.98
Removing intermediate container 0abc4a304b7b
 ---> c85245dd0872

Step 10/15 : FROM build AS publish
 ---> c85245dd0872
Step 11/15 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in fa10cfdb0836
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /src/src/BuildingBlocks/EventBus/EventBus/bin/Release/netstandard2.0/EventBus.dll
  EventBusRabbitMQ -> /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/netstandard2.0/EventBusRabbitMQ.dll
  Microsoft.Extensions.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.dll
  Microsoft.Extensions.HealthChecks.AzureStorage -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.AzureStorage/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.AzureStorage.dll
  Microsoft.AspNetCore.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/bin/Release/netstandard2.0/Microsoft.AspNetCore.HealthChecks.dll
  EventBusServiceBus -> /src/src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/netstandard2.0/EventBusServiceBus.dll
  WebHost.Customization -> /src/src/BuildingBlocks/WebHostCustomization/WebHost.Customization/bin/Release/netcoreapp2.0/WebHost.Customization.dll
  Marketing.API -> /src/src/Services/Marketing/Marketing.API/bin/Release/netcoreapp2.0/Marketing.API.dll
  Marketing.API -> /app/
Removing intermediate container fa10cfdb0836
 ---> cf10f3e5cd58

Step 12/15 : FROM base AS final
 ---> 0c773cd8f37f
Step 13/15 : WORKDIR /app
 ---> Using cache
 ---> 313e17ef950b
Step 14/15 : COPY --from=publish /app .
 ---> 0096c206f1ab
Step 15/15 : ENTRYPOINT ["dotnet", "Marketing.API.dll"]
 ---> Running in e75efd08391e
Removing intermediate container e75efd08391e
 ---> 06a152082c19

Successfully built 06a152082c19
Successfully tagged eshop/marketing.api:latest
WARNING: Image for service marketing.api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building catalog.api
Step 1/15 : FROM microsoft/aspnetcore:2.0.3 AS base
 ---> 7f83f41eee6d
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> c52a5b913ae0
Step 3/15 : EXPOSE 80
 ---> Using cache
 ---> 0c773cd8f37f

Step 4/15 : FROM microsoft/aspnetcore-build:2.0 AS build
 ---> 6105426f13e9
Step 5/15 : WORKDIR /src
 ---> Using cache
 ---> 4513e633d04d
Step 6/15 : COPY . .
 ---> Using cache
 ---> 66e1a34dfe17
Step 7/15 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> af1229934724
Step 8/15 : WORKDIR /src/src/Services/Catalog/Catalog.API
Removing intermediate container 77aef37649ba
 ---> 6cb58d49ac84
Step 9/15 : RUN dotnet build --no-restore -c Release -o /app
 ---> Running in 19f97110960a
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /app/EventBus.dll
  EventBusRabbitMQ -> /app/EventBusRabbitMQ.dll
  EventBusServiceBus -> /app/EventBusServiceBus.dll
  IntegrationEventLogEF -> /app/IntegrationEventLogEF.dll
  Microsoft.Extensions.HealthChecks -> /app/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /app/Microsoft.AspNetCore.HealthChecks.dll
  Microsoft.Extensions.HealthChecks.AzureStorage -> /app/Microsoft.Extensions.HealthChecks.AzureStorage.dll
  Microsoft.Extensions.HealthChecks.SqlServer -> /app/Microsoft.Extensions.HealthChecks.SqlServer.dll
  WebHost.Customization -> /app/WebHost.Customization.dll
  Catalog.API -> /app/Catalog.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:47.36
Removing intermediate container 19f97110960a
 ---> eb522a2ad27b

Step 10/15 : FROM build AS publish
 ---> eb522a2ad27b
Step 11/15 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in 2b599f9e3c4c
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /src/src/BuildingBlocks/EventBus/EventBus/bin/Release/netstandard2.0/EventBus.dll
  EventBusRabbitMQ -> /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/netstandard2.0/EventBusRabbitMQ.dll
  EventBusServiceBus -> /src/src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/netstandard2.0/EventBusServiceBus.dll
  Microsoft.Extensions.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/bin/Release/netstandard2.0/Microsoft.AspNetCore.HealthChecks.dll
  WebHost.Customization -> /src/src/BuildingBlocks/WebHostCustomization/WebHost.Customization/bin/Release/netcoreapp2.0/WebHost.Customization.dll
  Microsoft.Extensions.HealthChecks.AzureStorage -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.AzureStorage/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.AzureStorage.dll
  Microsoft.Extensions.HealthChecks.SqlServer -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.SqlServer.dll
  IntegrationEventLogEF -> /src/src/BuildingBlocks/EventBus/IntegrationEventLogEF/bin/Release/netstandard2.0/IntegrationEventLogEF.dll
  Catalog.API -> /src/src/Services/Catalog/Catalog.API/bin/Release/netcoreapp2.0/Catalog.API.dll
  Catalog.API -> /app/
Removing intermediate container 2b599f9e3c4c
 ---> ac4ecb657126

Step 12/15 : FROM base AS final
 ---> 0c773cd8f37f
Step 13/15 : WORKDIR /app
 ---> Using cache
 ---> 313e17ef950b
Step 14/15 : COPY --from=publish /app .
 ---> d743c5dd3c4b
Step 15/15 : ENTRYPOINT ["dotnet", "Catalog.API.dll"]
 ---> Running in 46a999774015
Removing intermediate container 46a999774015
 ---> cd1252ea611a

Successfully built cd1252ea611a
Successfully tagged eshop/catalog.api:latest
WARNING: Image for service catalog.api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building ordering.api
Step 1/15 : FROM microsoft/aspnetcore:2.0.3 AS base
 ---> 7f83f41eee6d
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> c52a5b913ae0
Step 3/15 : EXPOSE 80
 ---> Using cache
 ---> 0c773cd8f37f

Step 4/15 : FROM microsoft/aspnetcore-build:2.0 AS build
 ---> 6105426f13e9
Step 5/15 : WORKDIR /src
 ---> Using cache
 ---> 4513e633d04d
Step 6/15 : COPY . .
 ---> Using cache
 ---> 66e1a34dfe17
Step 7/15 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> af1229934724
Step 8/15 : WORKDIR /src/src/Services/Ordering/Ordering.API
Removing intermediate container 97c15941161b
 ---> c69cf4e739a1
Step 9/15 : RUN dotnet build --no-restore -c Release -o /app
 ---> Running in 798a033474cc
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /app/EventBus.dll
  WebHost.Customization -> /app/WebHost.Customization.dll
  EventBusRabbitMQ -> /app/EventBusRabbitMQ.dll
  EventBusServiceBus -> /app/EventBusServiceBus.dll
  IntegrationEventLogEF -> /app/IntegrationEventLogEF.dll
  Microsoft.Extensions.HealthChecks -> /app/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /app/Microsoft.AspNetCore.HealthChecks.dll
  Microsoft.Extensions.HealthChecks.SqlServer -> /app/Microsoft.Extensions.HealthChecks.SqlServer.dll
  Ordering.Domain -> /app/Ordering.Domain.dll
  Ordering.Infrastructure -> /app/Ordering.Infrastructure.dll
  Ordering.API -> /app/Ordering.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:02.94
Removing intermediate container 798a033474cc
 ---> 303673236190

Step 10/15 : FROM build AS publish
 ---> 303673236190
Step 11/15 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in c22733ac3922
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EventBus -> /src/src/BuildingBlocks/EventBus/EventBus/bin/Release/netstandard2.0/EventBus.dll
  Ordering.Domain -> /src/src/Services/Ordering/Ordering.Domain/bin/Release/netstandard2.0/Ordering.Domain.dll
  EventBusRabbitMQ -> /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/netstandard2.0/EventBusRabbitMQ.dll
  EventBusServiceBus -> /src/src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/netstandard2.0/EventBusServiceBus.dll
  IntegrationEventLogEF -> /src/src/BuildingBlocks/EventBus/IntegrationEventLogEF/bin/Release/netstandard2.0/IntegrationEventLogEF.dll
  Microsoft.Extensions.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/bin/Release/netstandard2.0/Microsoft.AspNetCore.HealthChecks.dll
  Microsoft.Extensions.HealthChecks.SqlServer -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.SqlServer.dll
  WebHost.Customization -> /src/src/BuildingBlocks/WebHostCustomization/WebHost.Customization/bin/Release/netcoreapp2.0/WebHost.Customization.dll
  Ordering.Infrastructure -> /src/src/Services/Ordering/Ordering.Infrastructure/bin/Release/netstandard2.0/Ordering.Infrastructure.dll
  Ordering.API -> /src/src/Services/Ordering/Ordering.API/bin/Release/netcoreapp2.0/Ordering.API.dll
  Ordering.API -> /app/
Removing intermediate container c22733ac3922
 ---> df3c3f92f4e7

Step 12/15 : FROM base AS final
 ---> 0c773cd8f37f
Step 13/15 : WORKDIR /app
 ---> Using cache
 ---> 313e17ef950b
Step 14/15 : COPY --from=publish /app .
 ---> 45e74e48a0fc
Step 15/15 : ENTRYPOINT ["dotnet", "Ordering.API.dll"]
 ---> Running in 85abb9918640
Removing intermediate container 85abb9918640
 ---> a0bdffadffb4

Successfully built a0bdffadffb4
Successfully tagged eshop/ordering.api:latest
WARNING: Image for service ordering.api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building webspa
Step 1/15 : FROM microsoft/aspnetcore:2.0.3 AS base
 ---> 7f83f41eee6d
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> c52a5b913ae0
Step 3/15 : EXPOSE 80
 ---> Using cache
 ---> 0c773cd8f37f

Step 4/15 : FROM microsoft/aspnetcore-build:2.0 AS build
 ---> 6105426f13e9
Step 5/15 : WORKDIR /src
 ---> Using cache
 ---> 4513e633d04d
Step 6/15 : COPY . .
 ---> Using cache
 ---> 66e1a34dfe17
Step 7/15 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> af1229934724
Step 8/15 : WORKDIR /src/src/Web/WebSPA
Removing intermediate container 9dc4e066aa17
 ---> 86594b4a89d0
Step 9/15 : RUN dotnet build --no-restore -c Release -o /app
 ---> Running in 72ef06845f88
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.Extensions.HealthChecks -> /app/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /app/Microsoft.AspNetCore.HealthChecks.dll
  WebSPA -> /app/WebSPA.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:30.17
Removing intermediate container 72ef06845f88
 ---> 42943b97e6c5

Step 10/15 : FROM build AS publish
 ---> 42943b97e6c5
Step 11/15 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in 07ce073258e4
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.Extensions.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/bin/Release/netstandard2.0/Microsoft.Extensions.HealthChecks.dll
  Microsoft.AspNetCore.HealthChecks -> /src/src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/bin/Release/netstandard2.0/Microsoft.AspNetCore.HealthChecks.dll
  WebSPA -> /src/src/Web/WebSPA/bin/Release/netcoreapp2.0/WebSPA.dll
 Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 324, in ensure_image_exists
  File "compose\service.py", line 972, in build
  File "compose\progress_stream.py", line 23, in stream_output
  File "compose\progress_stream.py", line 90, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
PS C:\dev\eShopOnContainers>
```

**Comment by Kaidanov** [comment]
acivated 4-th time 
got 
ERROR: for basket.data  Cannot start service basket.data: driver failed programming external connectivity on endpoint eshoponcontainers_basket.data_1 (98cb049874b54ce68b04203cd89fc7a7e918eeeb39aa5de9e994a5f41aa2e382): Timed out proxy starting the userland proxy
ERROR: Encountered errors while bringing up the project.

**Comment by CESARDELATORRE** [comment]
That is an issue in your environment. The Redis cache and probably other infrastructure containers are not able to start because they need more memory. The SQL Server container needs more, too.
You need to assing 4096 memory to Docker, as we explain in the Wiki:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

Set 4096 to Docker. That's why you usually will need a 16GB machine:
![image](https://user-images.githubusercontent.com/1712635/36118020-84506b8a-0ff0-11e8-9fb4-3ef68a4bf5ff.png)

With no issues with the infrastructure/memory like those, it should take less around 1h for setting it up, as confirmed by many devs using it.

**Comment by Kaidanov** [comment]
thanks
