### ISSUE TITLE
IntegrationEventLogEntry is using unsupported EF storage type

### ISSUE THREAD

**Issue by Eneuman** [dotnet-architecture/eShopOnContainers#514]
The property State in IntegrationEventLogEntry is a enum.
https://github.com/dotnet-architecture/eShopOnContainers/blob/b1ce2f90ea6e619f95c90880885d3eff6715a417/src/BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEntry.cs#L23

https://github.com/dotnet-architecture/eShopOnContainers/blob/b1ce2f90ea6e619f95c90880885d3eff6715a417/src/BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogContext.cs#L37

Enums are not currently supported by EF Core as storage type.
(But might be in EF Core 2.1 using the type convertion feature)

This leads to the following line
https://github.com/dotnet-architecture/eShopOnContainers/blob/b1ce2f90ea6e619f95c90880885d3eff6715a417/src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs#L45

will throw this error under some circumstances.

```
Unable to cast object of type 'System.String' to type 'System.Int32'.
   at lambda_method(Closure , Object[] )
   at Microsoft.EntityFrameworkCore.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
```

I would suggest switching out the enum for enumeration classes.
I can create a PR for this if you want.

**Comment by mvelosop** [comment]
Hi @Eneuman, enums ARE supported in EF Core 2.0, I'm pretty sure even from 1.0.

Could you elaborate on the circumstances where that error occurs?

It doesn't make much sense to use an enumeration class for this simple use case, as this is basically plumbing that shouldn't change because of user requirements changes, where enum classes could make a difference.

**Comment by Eneuman** [comment]
Hi
I found my problem and it looks like it's a type bug with enums in EF Core 2.0
https://github.com/aspnet/EntityFrameworkCore/issues/10293 so I'm going to close this and track it in EF Core repo.
