### ISSUE TITLE
DispatchDomainEventsAsync: Task.WhenAll causes EF "A second operation started on this context before a previous operation completed"?

### ISSUE THREAD

**Issue by sm-g** [dotnet-architecture/eShopOnContainers#575]
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/MediatorExtension.cs#L29

Sometimes I got 
```
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.AsyncEnumerable.AsyncEnumerableAdapter`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
---  ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
---  ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
---  ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
---  ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyCode.UserRepository.<GetUsers>d__4.MoveNext()
```

when have two domain events to handle and each handler queries DB (same DbContext).

see also
https://stackoverflow.com/questions/24702183/does-entity-framework-support-parallel-async-queries

**Comment by raboud** [comment]
do you have a stack trace?

**Comment by sm-g** [comment]
@raboud added more stacktrace lines in post

@CESARDELATORRE added link to eShopOnContainers code, which I use in my project. In eShop maybe there is no >=2 domain events which handlers working with same DbContext at all, but code still invalid.

**Comment by mvelosop** [comment]
Closing as this is not an issue of eShopOnContainers right now.

**Comment by sm-g** [comment]
@mvelosop I do not understand, why this is not an issue? This project is sample of how to do things.

**Comment by mvelosop** [comment]
Hi @sm-g,

What you pointed out looks like a real issue, **no questioning about that**.

It's just a matter of context.

Within the context of eShopOnContainers, this is not a problem, i.e. it's not causing any issue with the functioning or the purpose of the app.

The app is intended to be a guidance, to showcase architectural patterns, not to cope with all the details, or solve all the problems for a real production app, even though it does cover a lot of details.

So, exploring and solving this issue in eShopOnContainers, in a meaningful and verifiable way, would mean adding scenarios that are not within the scope of this app right now and that's the reason for closing the issue.

I hope this brief note helps, and makes it clear that this not about disregarding the issue per se.

Best regards.
