### ISSUE TITLE
Prod:Build for WebSPA erroring on UglifyJS

### ISSUE THREAD

**Issue by xxjhansonxx** [dotnet-architecture/eShopOnContainers#620]
When I try to build the WebSPA using npm run build:prod, I keep getting the below error apparently in UglifyJs:
```
PS C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA> npm run build:prod
> eshopaspnetnetcoredockerspa@0.0.0 build:prod C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA
> ng build --prod --aot --extract-css
 11% building modules 14/15 modules 1 active ...modules\bootstrap\scss\bootstrap.scssTemplate parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  <div class="card">
    [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
      <div role="tab" id="{{panel.id}}-header" [attr.ar"): ng:///C:/Local-Web-Sites/eShopOnContainers/src/Web/WebSPA/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4              Date: 2018-05-30T17:00:09.518Z
Hash: a43eaeba0bf97c7bfcd6
Time: 43216ms
chunk {0} polyfills.a84bc1ef821ea980ec2e.bundle.js (polyfills) 63.1 kB {4} [initial] [rendered]
chunk {1} styles.e01a405a925adca90fe6.bundle.css (styles) 107 kB {4} [initial] [rendered]
chunk {2} main.c420f8a82e1e3cc55d8c.bundle.js (main) 143 kB {3} [initial] [rendered]
chunk {3} vendor.99f2d26e28d7c7d776dd.bundle.js (vendor) 2.81 MB [initial] [rendered]
chunk {4} inline.9e7def55fe72b140f665.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in vendor.99f2d26e28d7c7d776dd.bundle.js from UglifyJs
Unexpected token: name (HttpError) [vendor.99f2d26e28d7c7d776dd.bundle.js:34915,6]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eshopaspnetnetcoredockerspa@0.0.0 build:prod: `ng build --prod --aot --extract-css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eshopaspnetnetcoredockerspa@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxx\AppData\Roaming\npm-cache\_logs\2018-05-30T17_00_09_694Z-debug.log
PS C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA>
```
With the below log file mentioned:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@6.1.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle eshopaspnetnetcoredockerspa@0.0.0~prebuild:prod: eshopaspnetnetcoredockerspa@0.0.0
6 info lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: eshopaspnetnetcoredockerspa@0.0.0
7 verbose lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: PATH: C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\xxxxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxxxx\AppData\Roaming\npm
9 verbose lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: CWD: C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA
10 silly lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: Args: [ '/d /s /c', 'ng build --prod --aot --extract-css' ]
11 silly lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: Returned: code: 1  signal: null
12 info lifecycle eshopaspnetnetcoredockerspa@0.0.0~build:prod: Failed to exec build:prod script
13 verbose stack Error: eshopaspnetnetcoredockerspa@0.0.0 build:prod: `ng build --prod --aot --extract-css`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid eshopaspnetnetcoredockerspa@0.0.0
15 verbose cwd C:\Local-Web-Sites\eShopOnContainers\src\Web\WebSPA
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
18 verbose node v8.9.4
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error eshopaspnetnetcoredockerspa@0.0.0 build:prod: `ng build --prod --aot --extract-css`
22 error Exit status 1
23 error Failed at the eshopaspnetnetcoredockerspa@0.0.0 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I can get the dev build to run just fine.  This was a fresh clone from the repo.

I've looked everywhere I could online and the only references were with webpack, es5 vs es6, and Babel.  Could someone point me in the right direction/configuration to resolve this?
Visual Studio 17 Pro V15.5.4, Windows 10, NPM V6.1.0

**Comment by mvelosop** [comment]
Hi @xxjhansonxx, it looks like you are running the command from PS in your computer, is that right?

**Comment by xxjhansonxx** [comment]
@mvelosop Yup, that's correct, PS running as admin.  

I looked a little further and it might be an issue with the version of angular cli, but I haven't upgraded that package yet to test.  The eShopContainers repo has ^1.3.0 and they mentioned this issue might be fixed in 1.5.

https://github.com/angular/angular-cli/issues/7756

**Comment by xxjhansonxx** [comment]
Installing angular/cli globally to 1.7.4 fixed the issue
`npm install -g @angular/cli`

I no longer see any uglify errors in PS.

**Comment by mvelosop** [comment]
Hi @xxjhansonxx, great you found the issue.

I was about to use this issue to showcase one of the wonders of Docker, because when running this command as part of the docker-compose, it completes ok, because the environment there is freezed!

you can try `docker-compose build webspa` from the cli to verify.

You could also submit that fix a as PR, to get you started 😉 

Thanks!

**Comment by xxjhansonxx** [comment]
@mvelosop Ahh, that is right!  I think it is mentioned in the WIKI for the setup and I completely forgot.  Thanks again and I'll try the PR.  Everything is running smoothly and I love how VS sets up the debugger for different processes.  Brilliant.

**Comment by mvelosop** [comment]
Yeah @xxjhansonxx, you're right, that was an absolutely brilliant feature from the VS team!

I'm closing this issue now, but you can reference it anyway when you get to prepare the PR.

Thanks!
