### ISSUE TITLE
Error login user "Unauthorised_client" . Build on Ubuntu Server

### ISSUE THREAD

**Issue by minhvc** [dotnet-architecture/eShopOnContainers#684]
Environment: Ubuntu 17.10 as a standalone server. Core i7, 32GB RAM, 256 SSD.
I have modified
.env file:
ESHOP_EXTERNAL_DNS_NAME_OR_IP=192.168.1.9
ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.1.9
.docker-compose.override.yml file
webmvc:
environment:
- IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105

error log:
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://0.0.0.0:80: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

![image](https://user-images.githubusercontent.com/4718379/43312252-e2ab3794-91b6-11e8-8bf3-b9c7d09c7555.png)

**Comment by minhvc** [comment]
when user login:
- log of system
identity.api_1              | fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
identity.api_1              |       Request validation failed
identity.api_1              | fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
when execute a command:
- docker exec -it cb8663560129 dotnet Identity.API.dll

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://0.0.0.0:80: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()

**Comment by mvelosop** [comment]
Hi @minhvc,

When you run `docker exec -it cb8663560129 dotnet Identity.API.dll` you are running that command in a running container but that container is precisely running that very same command because it's the Dockerfile's ENTRYPOINT so port 80 is being used by the same Identity.API.dll.

Please check the IP addresses in this table and change `localhost` to your IP address (seems to be 192.168.1.9)

![image](https://user-images.githubusercontent.com/7357806/43650393-875747c6-9737-11e8-8833-78cb29ebc756.png)

You can use [Microsoft SQL Operations Studio](https://docs.microsoft.com/en-us/sql/sql-operations-studio/what-is?view=sql-server-2017) from Linux instead of SSMS in Windows.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue but feel free to comment. Will reopen if needed.
